import { listingThumb, northsideGallery } from "@/lib/northside-images";

export type ListingCategory = "studio" | "shared" | "summer" | "northside" | "loft";

export type MarketplaceListing = {
  id: number;
  title: string;
  location: string;
  price: string;
  priceNum: number;
  dates: string;
  description: string;
  image: string;
  categories: ListingCategory[];
  badges: string[];
  verified: boolean;
  distanceMi: number;
  /** Approximate map pin (UTD vicinity demo). */
  position: { lat: number; lng: number };
};

export const marketplaceListings: MarketplaceListing[] = [
  {
    id: 1,
    title: "Sunny 1BR · Northside Residences",
    location: "Northside · 0.3 mi from UTD",
    price: "$780",
    priceNum: 780,
    dates: "May 15 – Aug 10 · Furnished",
    description:
      "Corner unit with full kitchen, in-unit laundry, and one covered parking spot. Steps from Northside retail and Comet Cruiser.",
    image: listingThumb.northside1,
    categories: ["northside", "summer", "studio"],
    badges: ["Verified student", "Lease on file"],
    verified: true,
    distanceMi: 0.3,
    position: { lat: 33.0014, lng: -96.7808 },
  },
  {
    id: 2,
    title: "Loft with skyline light",
    location: "Northside · 0.4 mi",
    price: "$735",
    priceNum: 735,
    dates: "Jun 1 – Aug 20",
    description: "Tall ceilings, walk-in closet, quiet floor. Ideal for internship summers.",
    image: listingThumb.loft,
    categories: ["northside", "loft", "summer"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 0.4,
    position: { lat: 33.0009, lng: -96.7795 },
  },
  {
    id: 3,
    title: "Private room in 2BR — friendly roommate",
    location: "University Village · 0.2 mi",
    price: "$540",
    priceNum: 540,
    dates: "May 20 – Aug 5",
    description: "Shared bath with one other UTD junior. Study-friendly, utilities split evenly.",
    image: listingThumb.uv,
    categories: ["shared", "summer"],
    badges: ["Verified student", "Lease on file"],
    verified: true,
    distanceMi: 0.2,
    position: { lat: 32.9884, lng: -96.7441 },
  },
  {
    id: 4,
    title: "Quiet studio · Waterview",
    location: "Waterview Pkwy · 0.8 mi",
    price: "$650",
    priceNum: 650,
    dates: "Jun 1 – Aug 15",
    description:
      "Kitchenette, blackout shades, pool access. Perfect if you want less foot traffic than Northside.",
    image: listingThumb.waterview,
    categories: ["studio", "summer"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 0.8,
    position: { lat: 32.9932, lng: -96.7545 },
  },
  {
    id: 5,
    title: "Northside 2BR — full apartment takeover",
    location: "Northside · 0.35 mi",
    price: "$1,120",
    priceNum: 1120,
    dates: "May 10 – Aug 25",
    description:
      "Both bedrooms available — bring a roommate or we can help pair through SubletSync.",
    image: listingThumb.northside2,
    categories: ["northside", "summer", "shared"],
    badges: ["Verified student", "Lease on file"],
    verified: true,
    distanceMi: 0.35,
    position: { lat: 33.0018, lng: -96.7812 },
  },
  {
    id: 6,
    title: "Summer crash pad — flexible dates",
    location: "Northside · 0.5 mi",
    price: "$695",
    priceNum: 695,
    dates: "±7 days flexible",
    description:
      "Light-filled unit, premium Wi-Fi included. Owner verified with prior successful sublease on platform.",
    image: listingThumb.matchExtra1,
    categories: ["northside", "summer", "studio"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 0.5,
    position: { lat: 33.0005, lng: -96.7788 },
  },
  {
    id: 7,
    title: "2BR split near Breckinridge Park",
    location: "Buckingham Rd · 1.1 mi",
    price: "$820",
    priceNum: 820,
    dates: "Jun 1 – Aug 12",
    description:
      "Second bedroom setup as office; quiet complex with pool. Good if you have a car or bike to campus.",
    image: listingThumb.matchExtra2,
    categories: ["studio", "summer"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 1.1,
    position: { lat: 32.9982, lng: -96.7268 },
  },
  {
    id: 8,
    title: "Room in 3BR · Cambria Apartments",
    location: "Renner Rd · 1.35 mi",
    price: "$495",
    priceNum: 495,
    dates: "May 25 – Aug 1",
    description: "Furnished common areas, in-unit laundry. Roommates are grad students.",
    image: northsideGallery[5]!.src,
    categories: ["shared", "summer"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 1.35,
    position: { lat: 32.9755, lng: -96.7388 },
  },
  {
    id: 9,
    title: "CityLine studio · Red line walk",
    location: "Bush Turnpike · 2.05 mi",
    price: "$925",
    priceNum: 925,
    dates: "May 10 – Aug 20",
    description: "Corporate-style finish, 24h desk. Slightly higher rent but shorter Uber to legacy employers.",
    image: northsideGallery[6]!.src,
    categories: ["studio", "summer"],
    badges: ["Verified student", "Lease on file"],
    verified: true,
    distanceMi: 2.05,
    position: { lat: 32.9555, lng: -96.702 },
  },
  {
    id: 10,
    title: "Garage townhome · Telecom Corridor",
    location: "Coit Rd · 1.65 mi",
    price: "$1,050",
    priceNum: 1050,
    dates: "Jun 5 – Aug 18",
    description: "Two floors, attached garage, pet-friendly. Fit for co-interns splitting rent.",
    image: northsideGallery[4]!.src,
    categories: ["northside", "loft", "summer"],
    badges: ["Verified student", "Lease on file"],
    verified: true,
    distanceMi: 1.65,
    position: { lat: 32.9682, lng: -96.7688 },
  },
  {
    id: 11,
    title: "Summer sublet · Arapaho station",
    location: "Arapaho Rd · 2.45 mi",
    price: "$610",
    priceNum: 610,
    dates: "May 1 – Aug 8",
    description: "Older build, huge square footage; DART Red Line one block for airport runs.",
    image: northsideGallery[3]!.src,
    categories: ["shared", "summer"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 2.45,
    position: { lat: 32.942, lng: -96.74 },
  },
  {
    id: 12,
    title: "Furnished 1BR · Galatyn Park",
    location: "Galatyn Park · 2.75 mi",
    price: "$890",
    priceNum: 890,
    dates: "Jun 10 – Aug 30",
    description: "Walk to Urban Crust and events; 10-minute drive to UTD during light traffic.",
    image: northsideGallery[2]!.src,
    categories: ["studio", "summer", "loft"],
    badges: ["Verified student"],
    verified: true,
    distanceMi: 2.75,
    position: { lat: 32.9485, lng: -96.709 },
  },
];
